# Generated by Django 4.0.4 on 2022-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vehicle_description',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
